**Ex 1**

In [80]:
import numpy as np

arr = np.ones(8)
arr2 = np.random.randint(0,10,8)
arr3 = arr + arr2
print(arr3)
soma = sum(arr3)
print(soma)

if(soma > 40):
  mtz = arr3.reshape(4,2)
  print(mtz)
else:
  mtz = arr3.reshape(2,4)
  print(mtz)




[10.  9.  8.  7.  5.  1.  8.  1.]
49.0
[[10.  9.]
 [ 8.  7.]
 [ 5.  1.]
 [ 8.  1.]]


**Ex 2**

In [81]:
mtz = np.zeros([2, 2])
mtz[np.random.randint(0, 2), np.random.randint(0, 2)] = 1

contador_seguros = 0
jogando = True

while jogando:
    linha = int(input("Insira a linha (0 ou 1): "))
    coluna = int(input("Insira a coluna (0 ou 1): "))

    if mtz[linha, coluna] == 1:
        print("Você perdeu.")
        jogando = False
    elif mtz[linha, coluna] == 0:
        print("Posição segura!")
        contador_seguros += 1
        mtz[linha, coluna] = -1
        if contador_seguros == 3:
            print("Parabéns! Você venceu!")
            jogando = False
    else:
        print("Você já escolheu essa posição, tente outra!")

print(mtz)

Insira a linha (0 ou 1): 0
Insira a coluna (0 ou 1): 0
Posição segura!
Insira a linha (0 ou 1): 1
Insira a coluna (0 ou 1): 1
Você perdeu.
[[-1.  0.]
 [ 0.  1.]]


**Ex3**

In [ ]:
matriz = np.zeros((3, 5))
linhas, colunas = matriz.shape
total_elementos = linhas * colunas

if total_elementos % 2 == 0:
    classificacao = "par"
else:
    classificacao = "ímpar"

print(matriz)
print(f"Tamanho da matriz: {linhas} linhas e {colunas} colunas.")
print(f"Multiplicação (linhas x colunas): {total_elementos}")
print(f"Esta matriz poderia se tornar um vetor unidimensional com um número {classificacao} de elementos.")

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Tamanho da matriz: 3 linhas e 5 colunas.
Multiplicação (linhas x colunas): 15
Esta matriz poderia se tornar um vetor unidimensional com um número ímpar de elementos.


**Ex4**

In [ ]:
np.random.seed(10)
matri = np.random.randint(1, 51, [4, 4])
medialinha = np.mean(matri, axis=1)
mediacoluna = np.mean(matri, axis=0)
print(matri)
print()
print(medialinha)
print(mediacoluna)

print()
print(max(medialinha))
print(max(mediacoluna))

valores, contagens = np.unique(matri, return_counts=True)
for valor, contagem in zip(valores, contagens):
    print(f"O número {valor} aparece {contagem} vez(es)")

numeros_duplicados = valores[contagens == 2]

print("\nNúmeros que aparecem exatamente 2 vezes:", numeros_duplicados)



[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

[16.   33.75 34.5  23.75]
[29.75 24.25 33.75 20.25]

34.5
33.75
O número 1 aparece 2 vez(es)
O número 9 aparece 1 vez(es)
O número 10 aparece 2 vez(es)
O número 16 aparece 1 vez(es)
O número 26 aparece 1 vez(es)
O número 29 aparece 1 vez(es)
O número 30 aparece 2 vez(es)
O número 37 aparece 1 vez(es)
O número 41 aparece 1 vez(es)
O número 43 aparece 1 vez(es)
O número 49 aparece 1 vez(es)
O número 50 aparece 2 vez(es)

Números que aparecem exatamente 2 vezes: [ 1 10 30 50]


**Ex5**

In [ ]:
matriz_zeros = np.zeros([3, 3])
matriz_uns = np.ones([3, 3])
soma = matriz_zeros + matriz_uns
resultado = soma * 5
vetor = resultado.reshape(9)
print("Matriz de Zeros:")
print(matriz_zeros)
print()

print("Matriz de Uns:")
print(matriz_uns)
print()

print("Soma das matrizes:")
print(soma)
print()

print("Resultado multiplicado pelo escalar 5:")
print(resultado)
print()

print("Array unidimensional (reshaped):")
print(vetor)

Matriz de Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de Uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Soma das matrizes:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Resultado multiplicado pelo escalar 5:
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

Array unidimensional (reshaped):
[5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Ex6**

In [ ]:
vetor = np.arange(10, 31, 2)

maior_valor = np.max(vetor)
indice_maior = np.argmax(vetor)
print(maior_valor)
print(indice_maior)

menor_valor = np.min(vetor)
indice_menor = np.argmin(vetor)
print(menor_valor)
print(indice_menor)

soma_total = np.sum(vetor)
print(soma_total)

30
10
10
0
220


**Ex7**

In [ ]:
np.random.seed(7)

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

array_concatenado = np.concatenate((array1, array2))

matriz = array_concatenado.reshape([2, 5])

print(array1)
print()


print(array2)
print()


print(array_concatenado)
print()


print(matriz)

[ 5 10  7  4  4]

[ 8  8 10  8  9]

[ 5 10  7  4  4  8  8 10  8  9]

[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
